### ISSUE TITLE
MathML core versus Content ML relationship

### ISSUE THREAD

**Issue by fkuehnel** [w3c/mathml#218] opened 2020-05-30 22:34 UTC
Although MathML and content MathML may serve very different function, I'm very unclear about how core MathML will reconcile with content MathML. In a utopian world, one could think of content MathML being the same as core MathML without any CSS style elements.

What are your thoughts?

**Comment by davidcarlisle** [comment] 2020-05-31 08:44
Core is the major part of presentation MathML, with some less used or less well specified parts removed and the addition of specific layout specifications for web platform implementations.

So basically the relationship with Content MathML is essentially the same as the relationship between Presentation MathML and Content.

The current draft of MathML4 is an exact copy of MathML3 as we haven't started the redrafting yet. However the description of every Content MathML element in chapter 4 includes a suggested rendering in Presentation MathML. The vast majority of those Presentation MathML expressions are already in Core the main exception being a few instances of  `<mfenced>`  but they can easily be rewritten using the equivalent MathML Core `<mrow>` construct. So I would expect that when we update that chapter for MathML4, all  the sample renderings will be written in MathML Core.

It is possible to consider semantically attributing Presentation or Core MathML to aid accessibility and also aid reverse translation to Content MathML, proposals there are less advanced but there are several issues open related to that, the most recently discussed one being  
https://github.com/mathml-refresh/mathml/issues/217

**Comment by fkuehnel** [comment] 2020-06-01 03:47
David, thanks for your quick response. In summary, there is a substantial gap to bridge between presentation and semantics. From what I read it seems algorithmically easier to translate from content ML to presentation ML with suggested rendering templates.

However, the reverse needs annotations and there are several open issues with this approach.
Is this a fair characterization?

**Comment by davidcarlisle** [comment] 2020-06-01 08:04
> Is this a fair characterization?

er perhaps, but better to say there are issues going in either direction,  There are fundamental reasons why Content MathML isn't Presentation (or Core) MathML or why OpenMath isn't LaTeX.
One can address the issues to an extent but the fact that there are two aims isn't avoidable.

You could mark up everything in a purely semantic way as Strict Content MathML or OpenMath or lisp s-expressions  but typically people want to see x+y not (plus x y) so mapping to presentation you need some heuristics for "known" functions and some kind of style or transformation annotation to cover unknown functions and language or community variation in presentation.

Going the other way you can have a math presentation with apparently no implied meaning at all  \frac{=}{=} but it may be something just displayed for fun or perhaps it's a specific notation introduced in the previous paragraph. If you  allow people to enter arbitrary math layout expressions but hope to infer mathematical meaning or good accessible reading of the expressions you are going to need some method of giving extra, optional, semantic annotations. Chapter 5 of the MathML3 spec goes into some detail but the markup used there is rather verbose (and hard for anyone to generate correctly) so the current discussions are around whether a lighter weight mechanism of annotating presentation mathml with semantic hints could be devised.

**Comment by fred-wang** [comment] 2020-06-01 11:11
Can we close this as a duplicate of #47 ?

There is no plan to implement content mathml in browsers or have it in MathML Core, so it seems something that has to be decided for MathML full or/and polyfills. And whether content mathml is the future for adding semantics is also open.

**Comment by davidcarlisle** [comment] 2020-06-01 11:29
I'd say this is a request for information rather than a dup of that one which is tracking the core spec details,  but either way it may be closed without action I think.

**Comment by fred-wang** [comment] 2020-06-01 11:33
I'm trying to reduce the number of open issues for mathml core, and that one does not seem to be related to spec changes for core. It seems there are already several issues for semantic enhancement, so it would be nice if someone go over them and tries to group the thread or summarize the ideas.

**Comment by fkuehnel** [comment] 2020-06-02 04:37
David, Fred, I think we can close this issue. This is not a direct request to change MathML core. As David stated, my comments are more aligned with a request for information.

However, the current state of presentation MathML is not sufficient to render future or even re-processed LateX documents amenable to search for mathematical expressions.  Maybe, presentation ML is a good first step.

A mark up design that facilitates infusing semantics into formulas will accelerate numerous follow up technologies, one I can think of immediately is search.

I concur, even if there were a perfect mark up description of math presentation and semantics, we'd still face the issue how to infer semantics in legacy LaTeX documents!

**Closed as completed** 2020-06-02 07:31 UTC
