### ISSUE TITLE
Adopt concept of optional tags - in particular for `</mn>`, `</mi>` and `</mo>`

### ISSUE THREAD

**Issue by universemaster** [w3c/mathml#375] opened 2022-05-30 16:00 UTC
Some criticize mathml for being too verbose and heavy increasing the network payload. These criticisms are  a shame because one of the main attractions of mathml is that it more lightweight than the html output of KaTex and MathJax (including the SVG output).

A possible partial mediation to this criticism is to adopt the concept of optional tags.

The whatwg html spec for optional tags is [here]( https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) and an advocate has blogged about optional tags [here](https://meiert.com/en/blog/optional-html/).

Here is an example where the `mn`, `mi`, and `mo` closing tags add no additional information, and so could be inferred from the fact that another one of those three tags is started.

With closing tags:
``` html
<math>
  <msqrt>
    <mn>2</mn>
    <mi>r</mi>
    <mo>−</mo>
    <mn>1</mn>
  </msqrt>
</math>
```

Closing tags can be inferred
``` html
<math>
  <msqrt>
    <mn>2
    <mi>r
    <mo>−
    <mn>1
  </msqrt>
</math>
```

The `</msqrt>` could also be inferred from the close tag `</math>`.

**Comment by davidcarlisle** [comment] 2022-05-30 16:26
MathML uses xml or html parsing but in both cases the behaviour of the parser is not changable by mathml, so any changes would have to be raised in the appropriate specifications.

XML has nothing corresponding to optional end tags.  This could be declared in an SGML profile but not so many people use SGML these days and the relevant declarations were dropped from XML.

As you comment, HTML does have this but for a fixed set of elements, unlike SGML there is no declarative syntax to control the parser here, so this would require agreement to change the HTML parser specification, and the implementations in every  browser. Technically not impossible but there is a very high bar for getting any such change.

You could already omit the end tags of the final mn and msqrt as they would be closed by `</math>` .

Making `<mi>` auto-close `<mn>` would require the parser to know more about the content model of mn. It does not just allow text but also html so that

`<mi>r <mo>` could theoretically close the mi but `<mi>r <span>`  can not 

Currently mi parses as an unknown html element not as the mathml mi as mn is expecting html content. Changing the HTML parser at this stage is very difficult.

A view of an HTML parse of your example:

![image](https://user-images.githubusercontent.com/1268738/171031568-6716be3f-379e-4581-a2d2-17338193ab37.png)

**Comment by NSoiffer** [comment] 2022-06-02 16:51
As @davidcarlisle says, this is really a HTML parsing issue and as such, would need to be addressed by the HTML WG. From what I've heard, there is a huge bias in that group against changing the parser, but you are (of course) free to try to convince them to do so.

Closing because the issue is not in our hands.

**Closed as completed by NSoiffer** 2022-06-02 16:51 UTC
